### ISSUE TITLE
Should functions mimic undocumented behavior of their python equivalents?

### ISSUE THREAD

**Issue by Hrothen** [Hrothen/textwrap#5]
python's `textwrap.dedent` has an undocumented feature: it will remove all whitespace from whitespace-only lines (excluding newlines), and these lines won't be used in determining the least common margin to dedent. My gut feeling is that this is a weird thing for a `dedent` function to do, at least by default.

There are two questions here:
- Should `dedent` mimic this behavior?
- In general, should the function in this library attempt to closely mimic the behavior of their python counterparts, or should they do what I feel to be "correct"?

I don't have a good answer for the second question, for `dedent` there are a couple options:
- ignore whitespace-only lines entirely
- treat whitespace-only lines exactly like other lines
- mimic the python behavior
- add a flag that determines the behavior between those three

I'm leaning towards treating whitespace-only lines like other lines, as it's the most consistent behavior.

**Comment by bearcage** [comment]
I'd opt for the first, personally. Presumably if you're using this on actual user input someplace you'll want to rstrip the line too regardless, so whitespace-only seems like a separate concern to me. Also whitespace-only lines with anything on them but the end of line are kind of an antipattern, IMO.

**Comment by Hrothen** [comment]
That's a good point. However from a performance standpoint stripping the whitespace inside `dedent` might be faster, `dedent` needs to keep a copy of the broken lines to remove margins from, so I don't think it can fuse efficiently with adjacent passes over the same `Text`.

**Comment by Hrothen** [comment]
Decided to go with @aberghage's suggestion for `dedent`, performance concerns can be addressed later when I have benchmarks.

For the second question: "should this library hew as closely as possible to the python library's behavior, even when I think it's weird?". I think the answer is no.
